### ISSUE TITLE
Throwing a object reference error when using OAUTH connections

### ISSUE THREAD

**Issue by anasufovic** [rajyraman/Ryr.XrmToolBox.RecentItemsManager#2]
Using an OAUTH based connection string (using an appid and redirect url) the tool throws a "Object reference not set to an instance of an object" error. 

This is against a Dynamics 365 online instance where the standard style of connecting doesn't work due to security requirements. It works correctly in instances that use a standard Xrm toolbox connection. I don't believe I have seen this issue with other plugins.

`************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryr.XrmToolBox.RecentItemsManager.RecentItemsHelper.RetrieveRecentItemsForUsers(List``1 users)
   at Ryr.XrmToolBox.RecentItemsManager.MainControl.<LoadSettings>b__5_0(BackgroundWorker bw, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
`

**Comment by rajyraman** [comment]
I have to check with Tanguy for this one.

**Comment by rajyraman** [comment]
I was able to repro this issue today. I will have a look at this soon.
